# Generated by Django 5.0.7 on 2024-08-02 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_user_username_alter_otp_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 10, 22, 17, 795201, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userlockout',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
